### ISSUE TITLE
Blower Command Board schematic

### ISSUE THREAD

**Issue by mossmann** [starsimpson/ventinow#2]
Capture schematic in KiCad.

**Comment by mossmann** [comment]
I'd like to assign this one to myself. This board has only moderate complexity and seems like a good place to start.

**Comment by mossmann** [comment]
The original schematic refers to this as "Blower Command Board" while the service manual calls it "Turbine Control PCBA".

**Comment by starsimpson** [comment]
Updates at this repo: https://github.com/ventinow/blower-command-board
